### ISSUE TITLE
Lua Anti-DDoS addition

### ISSUE THREAD

**Issue by C0nw0nk** [bungle/awesome-resty#49]
I created a library that would be a good addition to your listing.

https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS

It is a javascript authentication page like Cloudflare, Bitmitigate and sucuri "I am under attack mode".

Looking to add my script to as many communities and lists as possible in order to help improve it! :)

**Comment by bungle** [comment]
Added.

**Comment by LoganDark** [comment]
> Legal Usage :
> For those who wish to use this in production you should contact me to purchase a private license to use this legally.
> For those who wish to use this in a commerical enviorment contact me to come to an agreement and purchase a commerical usage license.
> For those who wish to purchase the rights to this from me contact me also to discuss pricing and terms and come to a sensible agreement.

This does not exactly inspire confidence. The repository is otherwise unlicensed. @bungle are you sure this deserves a spot on the list?

**Comment by C0nw0nk** [comment]
I can remove / alter the copyright disclaimer if users wish. What is the
best disclaimer to use for opensource ?

**Comment by LoganDark** [comment]
The license your project is currently using is known as "all rights reserved" and that basically means that nobody can use your code without first contacting you and negotiating, which is not free or open source at all.

The best thing you can do for open-source is to use a permissive [open-source license](https://choosealicense.com/) rather than "contact me for details".

Even the SSPL ([Server-Side Public License](https://www.mongodb.com/licensing/server-side-public-license)), which requires users to make public their _entire software stack_ and its configuration, is more permissive than All Rights Reserved (however, it's not _exactly_ a free and open source license).

However, that is an extremely strong copyleft license to use for such a small script (a.k.a. it scares people away just like ARR), so I would recommend [MIT](https://choosealicense.com/licenses/mit/) instead, which requires preserving credit for your work, but not much else.

**Comment by C0nw0nk** [comment]
Thanks LoganDark, I will change it to MIT instead since it preserves credit
since I did not want to add "No License" because default copyright law
would have made it bad for users to engage with the project. But seeing how
popular it is I would like for the community to enjoy it and of course
those who contribute preserve credit for contributors too at that point so
it's a win all around.

I will do this right now.

**Comment by LoganDark** [comment]
> default copyright law would have made it bad for users to engage with the project

May I interest you in the [Unlicense](https://unlicense.org/) then?

**Comment by C0nw0nk** [comment]
Looks awesome, My only question is obviously contributors would want
crediting for their submissions, Maybe not all but some of them if i stick
with MIT this allows them credit if i make it unlicensed I assume their
contributions they have to explicitly say they want them to be licensed
unlicensed ?

**Comment by LoganDark** [comment]
> Looks awesome, My only question is obviously contributors would want crediting for their submissions, Maybe not all but some of them if i stick with MIT this allows them credit if i make it unlicensed I assume their contributions they have to explicitly say they want them to be licensed unlicensed ?

The MIT only requires preserving the copyright notice itself, not the credits of all contributors (unless of course you include them in the license notice). I was more referring to preserving credit of *you* (for example, "Copyright 2022 C0nw0nk", or your real name).

Common practice when providing credit to contributors is to have a `CONTRIBUTORS.md` that lists everyone who's made a significant contribution.

I'm not a lawyer, but a pull request usually serves as the disclaimer that the provided code is to be licensed under the repository's license, although a dedicated disclaimer never hurts (some repositories still require it). Note that this is separate from repositories requiring a CLA which does require a dedicated disclaimer, but that's a whole other can of worms.

(Basically, CLAs typically create the ability for the repository owner to *change* licenses without having to ask for permission from everyone who has ever contributed code, but pull requests do not include that grant by default. I would not recommend adopting one for your project, though)
